<div id="add_place_result" class="et-box et-download hidden">
    <div class="et-box-content">
        <p>
            Рибне місце додано. <a href="#" id="add_more">Додати ще одне рибне місце</a>
        </p>
        <p>
            <a href="" id="view_place">Переглянути додане місце</a>
        </p>
    </div>
</div>

<form id="add_place_form" method="POST" action="<?php echo admin_url('admin-ajax.php');?>">
    <input type="hidden" name="action" value="fish_map_add_place_save" />
    <div id="form_params">
        <div class="controls">
            <label for="marker_name">*Назва водойми</label>
            <input id="marker_name"
                   type="text"
                   name="name"
                   required="1"
                   class="qtip-info"
                   data-qtip="Загально відома назва місця для рибалки, наприклад Біле Озеро, Бочаниця" />
        </div>

        <div class="controls" class="marker_lat">
            <label>*Координати на мапі</label>
            <input type="hidden" name="lat" />
            <input type="hidden" name="lng" />

            <div id="map_canvas" class="google-map marker_lat" ></div>
            <small>(клікніть на карті, щоб позначити водойму)</small>
        </div>

        <div class="controls">
            <label for="marker_content">Інформація про водойму</label>
            <textarea id="marker_content"
                      name="content" rows="6" maxlength="10000"
                      class="qtip-info"
                      data-qtip="наприклад: Став був клубним і ловити було заборонено,
                лише обраним по запрошеннях. Проте тепер ставок відкритий для
                ловлі для всіх бажаючих. Отже, ставок знаходиться десь
                за 150-200 м справа від в'їзду в с.Півче зі сторони
                Мізоча (8 км від Мізоча). Ставок чистий, незарозший,
                з твердим дном"
            ></textarea>
        </div>

        <div class="controls">
            <label for="fishes">Виберіть рибу</label>

            <div class="fishes">
                <?php foreach ($fishes as $fish) { ?>
                    <div class="fish">
                        <label class="check">
                            <input type="checkbox" name="fishes[<?php echo $fish->fish_id ?>][fish_id]"
                                   value="<?php echo $fish->fish_id ?>" />
                            <?php echo $fish->name ?>
                        </label>
                        <input type="number" name="fishes[<?php echo $fish->fish_id ?>][amount]"
                               class="fish-amount qtip-info qtip-bottom" data-qtip="Кльов риби (1-10)"
                               value="" min="1" max="10" placeholder="klev" disabled="1" />
			<input type="number" name="fishes[<?php echo $fish->fish_id ?>][weight_avg]"
			       class="fish-amount qtip-info qtip-bottom" data-qtip="weight_avg in grams"
			       value="" min="10" step="10" placeholder="500" disabled="1"/>
                	<input type="number" name="fishes[<?php echo $fish->fish_id ?>][weight_max]"
			       class="fish-amount qtip-info qtip-bottom" data-qtip="weight_max in grams"
			       value="" min="10" step="10" placeholder="800" disabled="1"/>
                	<input type="text" name="fishes[<?php echo $fish->fish_id ?>][notes]"
			       class="fish-notes qtip-info qtip-bottom" data-qtip="write smth about fish"
			       value="" maxlength="255" placeholder="note" disabled="1"/>

		    </div>
                <?php } ?>
            </div>
        </div>

        <div class="controls">
            <label for="permit">Умови рибалки</label>
            <select name="permit" id="permit">
                <option value="unknown">невідомо</option>
                <option value="free">безкоштовно</option>
                <option value="paid">платно</option>
                <option value="prohibited">заборонено</option>
            </select>
        </div>

        <div class="controls hidden">
            <label for="marker_paid_fish">Вартість риболовлі</label>
            <input id="marker_paid_fish"
                   type="text"
                   name="paid_fish"
                   class="qtip-info"
                   data-qtip="ціна, час доби коли можна рибалити, вага риби на виніс і т.п." />
        </div>

        <div class="controls hidden">
            <label for="marker_contact">Контакт на водоймі</label>
            <input id="marker_contact" type="text" name="contact"
                   class="qtip-info"
                   data-qtip="телефон та ім'я чи т.п., щоб замовити місце, розпитати" />
        </div>

        <?php if ($showUploadPhotos) { ?>
            <div class="controls">
                <label>Фото водойми</label>
                <div id="upload_container">
                    <button id="photo_upload">Додати фото...</button>
                </div>

                <div id="loading" class="hidden"></div>
                <div id="pictures"></div>
            </div>
        <?php } ?>

        <div id="additional_opts" >

            <div class="controls hidden">
                <label for="marker_address">Адреса водойми</label>
                <input id="marker_address" type="text" name="address"
                       class="qtip-info"
                       data-qtip="наприклад 'село Бочаниця, Гощанський район, Рівненська область'" />
            </div>

            <div class="controls">
                <label for="marker_conveniences">Умови для відпочинку</label>
                <textarea id="marker_conveniences"
                          name="conveniences" rows="6" cols="62" maxlength="10000"
                          class="qtip-info"
                          data-qtip="чи є доступ до питної води, де ставити палатку, чи є мангали й столики і таке інше"
                ></textarea>
            </div>

            <div class="controls">
                <div class="col col-3">
                    <label for="marker_area">Площа водойми</label>
                    <input id="marker_area" type="text" name="area" class="input-sm qtip-info qtip-bottom"
                           data-qtip="в арах, 100 ар = 1 Га" />
                </div>
                <div class="col col-3">
                    <label for="marker_average_depth">Середня глибина</label>
                    <input id="marker_average_depth" type="text" name="average_depth"
                           class="input-sm qtip-info qtip-bottom"
                           data-qtip="в метрах" />
                </div>
                <div class="col col-3">
                    <label for="marker_max_depth">Максим. глибина</label>
                    <input id="marker_max_depth" type="text" name="max_depth"
                           class="input-sm qtip-info qtip-bottom"
                           data-qtip="в метрах" />
                </div>
            </div>

            <div class="controls hidden">
                <div class="col col-4">
                    <label for="marker_price_24h">Варість ловлі за добу</label>
                    <input id="marker_price_24h" type="text" name="price_24h"
                           class="input-sm qtip-info"
                           data-qtip="в гривнях" />
                </div>
                <div class="col col-4">
                    <label for="marker_dayhour_price">Варість ловлі за світловий день</label>
                    <input id="marker_dayhour_price" type="text" name="dayhour_price"
                           class="input-sm qtip-info"
                           data-qtip="в гривнях" />
                </div>
            </div>

            <div class="controls hidden">
                <label for="time_to_fish">Коли можна рибалити</label>
                <select id="time_to_fish" name="time_to_fish">
                    <option value="unknown">невідомо</option>
                    <option value="24h">цілодобово</option>
                    <option value="daylight">лише світловий день</option>
                </select>
            </div>

            <div class="controls hidden">
                <label for="marker_boat_usage">
                    <input type="hidden" name="boat_usage" value="0" />
                    <input id="marker_boat_usage" type="checkbox" name="boat_usage" value="1" />
                    можна користуватись човном
                </label>
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" name="add_submit" id="add_submit" class="submit"
                   value="Додати" />
        </div>
    </div>
</form>