<script type="text/javascript">
    var WP_AJAX_URL = "<?php echo admin_url('admin-ajax.php');?>";
    var WP_ADMIN = <?php echo current_user_can( 'manage_options' ) ? 'true' : 'false'; ?>;
</script>
<div id="et_main_map_wrapper">
    <div id="et_main_map" class="map_canvas"></div>
</div>

<div id="filter-bar">
    <div class="container">
        <!--form method="get" id="et-filter-map" action="<?php echo esc_url( home_url( '/' ) ); ?>">
            <a href="#" class="filter-type listing-type"><span class="et_explorable_filter_text"><?php esc_html_e( 'All Listing Types', 'Explorable' ); ?></span><span class="et_filter_arrow"></span></a>
            <a href="#" class="filter-type listing-location"><span class="et_explorable_filter_text"><?php esc_html_e( 'All Locations', 'Explorable' ); ?></span><span class="et_filter_arrow"></span></a>
            <a href="#" class="filter-type listing-rating"><span class="et_explorable_filter_text"><?php esc_html_e( 'Any Rating', 'Explorable' ); ?></span><span class="et_filter_arrow"></span></a>
            <button id="et-filter"><?php esc_html_e( 'Filter', 'Explorable' ); ?></button>
            <input type="hidden" value="" name="s" />
            <input type="hidden" value="listing" name="post_type" />

            <select name="et-listing-type" id="et-listing-type">
                <option value="none"><?php esc_html_e( 'All Listing Types', 'Explorable' ); ?></option>
            </select>

            <select name="et-listing-location" id="et-listing-location">
                <option value="none"><?php esc_html_e( 'All Locations', 'Explorable' ); ?></option>
            </select>

            <select name="et-listing-rating" id="et-listing-rating">
                <option value="none"><?php esc_html_e( 'Any Rating', 'Explorable' ); ?></option>
            </select>
        </form-->
        <div id="map_search">
            <div>
                <input type="text" id="addressInput" size="25" autocomplete="on"
                       title="Знайти адресу і показати всі водойми в зазначеному радіусі від неї"
                       placeholder="Пошук адреси"/>
                <select id="radiusSelect" title="Допустимі відстані 25км, 50км, 100км, 200км">
                    <option value="25" selected>25 km</option>
                    <option value="50">50 km</option>
                    <option value="100">100 km</option>
                    <option value="200">200 km</option>
                </select>
                <a id="search_button"
                   title="Всі рибні точки на відстані 25km, 50km,... від введеної адреси"
                   class="small-button smallsilver"
                >Шукати</a>
                <a id="show_all_button"
                   class="small-button smallsilver"
                >Показати всі точки</a>

                <div class="pull-right">
                    <a class="small-button smallblack" href="/lakes/add-fish-place/"
                    >Додати водойму</a>
                </div>
                <div class="pull-right">
                    <a class="small-button smallblack" href="/add-post/"
                    >Написати звіт</a>
                </div>
                
            </div>
            <div><select id="locationSelect" style="width:100%; display:none"></select></div>
        </div>
    </div> <!-- .container -->
</div> <!-- #filter-bar -->


<div id="et-list-view" class="et-normal-listings">
    <h2 id="listing-results"><?php esc_html_e( 'Рибні місця', 'Explorable' ); ?>
        <span id="markersListTotal" title="Всього водойм"></span>
    </h2>

    <div id="et-listings">
        <div id="markersFilterWrap">
        <input type="text" id="markersFilter" class="clearfix"
               autocomplete="off"
               title="Фільтрування водойм"
               placeholder="Фільтрування водойм"/>
        </div>
        <div class="viewport">
            <div class="overview">
                <ul id="markersList" >
                </ul>
                <div id="markersListTotal"></div>
            </div> <!-- .overview -->
        </div> <!-- .viewport -->
    </div> <!-- #et-listings -->
</div> <!-- #et-list-view -->
