<form id="report_form" method="POST" action="<?php echo admin_url('admin-ajax.php');?>">
    <input type="hidden" name="action" value="fish_map_save_report" />

    <div class="controls">
        <label for="report_name">*Заголовок звіту</label>
        <input id="report_name" type="text" name="name" required="1" />
    </div>
    
    <?php echo $text_editor ?>

    <div class="controls">
        <h3>Всі фото з рибалки</h3>
        <p>
            Після завантаження фото ви можете їх перетягувати у свій звіт мишею у зручне місце
        </p>

        <div id="upload_container">
            <button id="photo_upload">Додати фото...</button>
        </div>
        <div id="loading" class="hidden"></div>
        <div id="photos"></div>
        
    </div>

    <div class="form-actions">
        <input type="submit" name="add_submit" id="add_submit" class="submit"
               value="Додати звіт" />
    </div>
</form>

<div id="report_post_result" class="et-box et-download hidden">
    <div class="et-box-content">
        <p>
            Звіт додано. Модератор опублікує його найближчим часом.
        </p>
    </div>
</div>
